version: '3'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"

    webserver:
        image: puckel/docker-airflow
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - FERNET_KEY=C4XileCcLtsVI4SHEeyOmW4ObiUl1kII6m5uQ_VExNw=
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./requirements.txt:/requirements.txt
            - ./shared_files:/usr/local/airflow/shared_files
            - ../scripts_load_bq_tables:/usr/local/airflow/scripts_load_bq_tables
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    scheduler:
        container_name: "airflow_scheduler"
        restart: always
        image: puckel/docker-airflow
        depends_on: 
                - webserver
        environment:
                - LOAD_EX=n
                - FERNET_KEY=C4XileCcLtsVI4SHEeyOmW4ObiUl1kII6m5uQ_VExNw=
        command: scheduler